### ISSUE TITLE
Getting error while running example folder

### ISSUE THREAD

**Issue by jsphkhan** [mrjono1/joi-to-typescript#65]
Here is the issue that appears I run the script: 
```bash
npm run types
```

```js
Running joi-to-typescript...
TypeError: parsedSchema.children.flatMap is not a function
    at Object.getAllCustomTypes (/Users/josephkhan/htdocs/new-preparations/joi-to-typescript/example/node_modules/joi-to-typescript/dist/parse.js:27:38)
    at Object.convertSchema (/Users/josephkhan/htdocs/new-preparations/joi-to-typescript/example/node_modules/joi-to-typescript/dist/index.js:54:37)
    at Object.analyseSchemaFile (/Users/josephkhan/htdocs/new-preparations/joi-to-typescript/example/node_modules/joi-to-typescript/dist/analyseSchemaFile.js:29:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at main (/Users/josephkhan/htdocs/new-preparations/joi-to-typescript/example/node_modules/ts-node/src/bin.ts:198:14)
    at Object.<anonymous> (/Users/josephkhan/htdocs/new-preparations/joi-to-typescript/example/node_modules/ts-node/src/bin.ts:288:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

Is there something I am missing?

**Comment by mrjono1** [comment]
I'll have a look in a few days, I have only tested the example with yarn it is probably something to do with not having a package lock json for npm

**Comment by jsphkhan** [comment]
This is probably to do with my node version. Let me check and get back.

**Comment by jsphkhan** [comment]
bro it's working now. Pls, ignore. Have a good day!
